### ISSUE TITLE
Display password requirements on Register page

### ISSUE THREAD

**Issue by dkadyrov** [bs-haddad/genart#1]
What are/should be the password requirements? So I can adjust in Django backend (Daniel)

**Comment by bs-haddad** [comment]
> What are/should be the password requirements? So I can adjust in Django backend (Daniel)
> 

I'd think at least 6 characters, one upper, one lower, and either one number or symbol

**Comment by dkadyrov** [comment]
Why should we impose such strict password requirements on this site? We don't really have any private information?

**Comment by dkadyrov** [comment]
Currently addressed it to be a minimum of 6 characters.
