### ISSUE TITLE
New view for displaying generated art

### ISSUE THREAD

**Issue by derekwwil** [bs-haddad/genart#4]
I was messing around and created a few images. Each time I was re-directed to the home page after creating the image. I know that the first image is supposed to be the image i most recently created but sometimes it's very hard to tell depending on which images I used. Should there be an intermediate step between hitting "save" and being redirected to the home page? Should there be a page where the user can be previewed the art and can choose if they want to post it? There are no "emergency exits" or ways to edit the photo after the user has hit "save".

**Comment by derekwwil** [comment]
![image](https://user-images.githubusercontent.com/66653947/89296940-1b6b9b80-d631-11ea-897c-e83004a28a5c.png)

**Comment by derekwwil** [comment]
Maybe instead of the intermediate page, the user would still be directed to the homepage but their image was featured in its own row. Something that makes it stand out as the photo that was just created. There should probably be controls so the user could delete their own photos or maybe edit the title?

**Comment by dkadyrov** [comment]
I edited it so it redirects now to the art page of the new user's art. Someone still has to style that template to look like your wireframe.
